Repository ysmazaheri/NewsBridge, pull requests merged in 2025-03, with the labels that each got.

#32 Implement Reusable Fundamental Components
  frontend/newsbridge/package-lock.json
  frontend/newsbridge/package.json
  frontend/newsbridge/public/hidepassword.svg
  frontend/newsbridge/public/showpassword.svg
  frontend/newsbridge/public/trending.svg
  frontend/newsbridge/src/App.css
  frontend/newsbridge/src/App.tsx
  frontend/newsbridge/src/components/FormElements.tsx
  frontend/newsbridge/src/utils/constants.tsx
Labels: component development

#33 Implement Navbar with dynamic elements and reusable components
  frontend/newsbridge/public/NewsBridgeLogo.png
  frontend/newsbridge/public/ProfileIcon.png
  frontend/newsbridge/public/bookmarkicon.png
  frontend/newsbridge/public/searchicon.png
  frontend/newsbridge/public/searchicon.svg
  frontend/newsbridge/src/App.tsx
  frontend/newsbridge/src/components/Navbar.tsx
  frontend/newsbridge/src/components/ProfileDropdown.tsx
Labels: component development

#34 Implement Search Component and dropdown filter component with dynamic options
  frontend/newsbridge/package-lock.json
  frontend/newsbridge/package.json
  frontend/newsbridge/public/sorticon.svg
  frontend/newsbridge/src/components/Dropdown.tsx
  frontend/newsbridge/src/components/Navbar.tsx
  frontend/newsbridge/src/components/SearchComponent.tsx
Labels: component development

#41 Fix navbar scaling
  frontend/newsbridge/src/components/Navbar.tsx
  frontend/newsbridge/src/components/NavbarButton.tsx
  frontend/newsbridge/src/components/ProfileDropdown.tsx
Labels: bug

#37 Design reusable authentication form module and implement sign in component
  frontend/newsbridge/package-lock.json
  frontend/newsbridge/package.json
  frontend/newsbridge/src/App.tsx
  frontend/newsbridge/src/components/AuthenticationForm.tsx
  frontend/newsbridge/src/components/SignIn.tsx
Labels: component development

#42 Implement sign up and reset password components
  frontend/newsbridge/package-lock.json
  frontend/newsbridge/package.json
  frontend/newsbridge/src/App.tsx
  frontend/newsbridge/src/components/AuthenticationForm.tsx
  frontend/newsbridge/src/components/ResetPassword.tsx
  frontend/newsbridge/src/components/SignIn.tsx
  frontend/newsbridge/src/components/SignUp.tsx
Labels: component development

#45 Display dynamic password requirements as user types
  frontend/newsbridge/src/components/AuthenticationForm.tsx
  frontend/newsbridge/src/components/SignUp.tsx
  frontend/newsbridge/src/utils/validation.tsx
Labels: component development

#43 Implement log out component
  frontend/newsbridge/src/components/LogOut.tsx
  frontend/newsbridge/src/components/Navbar.tsx
  frontend/newsbridge/src/components/ProfileDropdown.tsx
Labels: component development

#40 Implemented the bias scale components
  frontend/newsbridge/src/App.tsx
  frontend/newsbridge/src/components/BiasScale.tsx
  frontend/newsbridge/src/pages/component_testing_pages/BiasScalePage.tsx
Labels: component development

#49 Completed the written comments section for user to enter comment
  frontend/newsbridge/public/submiticon.svg
  frontend/newsbridge/src/components/FormElements.tsx
  frontend/newsbridge/src/pages/component_testing_pages/FormElementsPage.tsx
Labels: component development

#50 Displayed user comment box
  frontend/newsbridge/public/person.svg
  frontend/newsbridge/src/components/CommentDisplay.tsx
  frontend/newsbridge/src/pages/component_testing_pages/FormElementsPage.tsx
Labels: component development

#47 Minor fix folder design
  frontend/newsbridge/package-lock.json
  frontend/newsbridge/package.json
  frontend/newsbridge/public/bookmarkicon.svg
  frontend/newsbridge/public/profileicon.svg
  frontend/newsbridge/public/trending.svg
  frontend/newsbridge/src/App.tsx
  frontend/newsbridge/src/components/Authentication/AuthenticationForm.tsx
  frontend/newsbridge/src/components/Navbar.tsx
  frontend/newsbridge/src/components/NavigationBar/Navbar.tsx
  frontend/newsbridge/src/components/NavigationBar/NavbarButton.tsx
  frontend/newsbridge/src/components/NavigationBar/ProfileDropdown.tsx
  frontend/newsbridge/src/components/SampleComponent.tsx
  frontend/newsbridge/src/components/Search/Dropdown.tsx
  frontend/newsbridge/src/components/Search/SearchComponent.tsx
  frontend/newsbridge/src/pages/ResetPassword.tsx
  frontend/newsbridge/src/pages/SamplePage.tsx
  frontend/newsbridge/src/pages/SignIn.tsx
  frontend/newsbridge/src/pages/SignUp.tsx
Labels: bug, styling & responsiveness

#51 Updating zindex of profile dropdown
  frontend/newsbridge/src/components/NavigationBar/ProfileDropdown.tsx
Labels: bug

#61 Comment Section Component
  frontend/newsbridge/src/components/CommentSection/CommentDisplay.tsx
  frontend/newsbridge/src/components/CommentSection/CommentSection.tsx
  frontend/newsbridge/src/components/FormElements.tsx
  frontend/newsbridge/src/entities/viewmodels/CommentVM.tsx
  frontend/newsbridge/src/mock-data/MockComments.tsx
  frontend/newsbridge/src/pages/Article.tsx
  frontend/newsbridge/src/pages/component_testing_pages/FormElementsPage.tsx
Labels: component development

#66 Implemented profile page with updated requirements
  frontend/newsbridge/public/Default_pfp.png
  frontend/newsbridge/src/App.tsx
  frontend/newsbridge/src/components/Authentication/LogOut.tsx
  frontend/newsbridge/src/components/DeleteAccount.tsx
  frontend/newsbridge/src/components/FormElements.tsx
  frontend/newsbridge/src/components/NavigationBar/ProfileDropdown.tsx
  frontend/newsbridge/src/entities/viewmodels/UserVM.tsx
  frontend/newsbridge/src/pages/Profile.tsx
Labels: page assembly

#74 Implement article page
  frontend/newsbridge/package-lock.json
  frontend/newsbridge/src/App.tsx
  frontend/newsbridge/src/components/Article/ArticlePreview.tsx
  frontend/newsbridge/src/components/Article/CommentSection/CommentDisplay.tsx
  frontend/newsbridge/src/components/Article/CommentSection/CommentSection.tsx
  frontend/newsbridge/src/components/Article/Partials/Bookmark.tsx
  frontend/newsbridge/src/components/Article/Partials/LikeButton.tsx
  frontend/newsbridge/src/components/Article/Partials/ShareButton.tsx
  frontend/newsbridge/src/components/Article/Partials/Sources.tsx
  frontend/newsbridge/src/components/BiasScale.tsx
  frontend/newsbridge/src/components/FormElements.tsx
  frontend/newsbridge/src/entities/viewmodels/ArticleVM.tsx
  frontend/newsbridge/src/entities/viewmodels/CommentVM.tsx
  frontend/newsbridge/src/mock-data/MockArticle.tsx
  frontend/newsbridge/src/mock-data/MockComments.tsx
  frontend/newsbridge/src/mock-data/MockSources.tsx
  frontend/newsbridge/src/mock-data/mockSourceArticles.tsx
  frontend/newsbridge/src/pages/Article.tsx
  frontend/newsbridge/src/pages/component_testing_pages/FormElementsPage.tsx
Labels: page assembly
